# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5633d64f6dd85be9faca10bf5600238cc923901b47141f1813176b86e7da5198143b6db7ed49670663f5dd049880583c5653e9170735a5d5d406e2519be92e4f

test:
  secret_key_base: f8ccd5d499bfe5ee8fbcc1496810ccc0a5847f5d4197543f07fb96e130b5ec486ad2167ddd31520d4649f6a04ef69d237bb3b9ce59a1c36ada28ffb14e0ba6d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
